allowBuilds:
  '@reown/appkit': false
  bufferutil: false
  cbor-extract: false
  esbuild: false
  keccak: false
  protobufjs: false
  utf-8-validate: false

packages:
  - 'packages/*'
  - 'server'
  - 'paylink_registry'
  - '.'